#!/data/data/com.termux/files/usr/bin/bash

start-adbd() {
    setprop service.adb.tcp.port 9999
    /system/bin/start adbd

    adb connect 127.0.0.1:9999
}

stop-adbd() {
     /system/bin/stop adbd
     setprop service.adb.tcp.port 0

     adb disconnect 127.0.0.1:9999
}

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit 1
fi

if [[ "$1" = "start" ]]
then
    echo start
    start-adbd
elif [[ "$1" = "stop" ]] then
    echo stop
    stop-adbd
else
    echo "start or stop"
    exit 1
fi
