#!/data/data/com.termux/files/usr/bin/env /data/data/com.termux/files/usr/bin/python

import json
import subprocess as sp
import re

class Handle:

    def __init__(self):
        self.data = self.readfile()
        self.default = '50:98:39:0f:bf:fc'

    @staticmethod
    def readfile():
        with open('data/mac.json') as file:
            return json.load(file)

    def change(self, mac):
        if self.checkvalid(mac):
            sp.run(('su', '-c', 'ifconfig', 'wlan0', 'down'))
            sp.run(('su', '-c', 'ifconfig', 'wlan0', 'hw', 'ether', mac))
            sp.run(('su', '-c', 'ifconfig', 'wlan0', 'up'))
        else:
            raise ValueError('MAC address is invalid')

    def reset(self):
        self.change(self.default)
        print('reset to default mac!')

    @staticmethod
    def checkvalid(mac):
    regex = ("^([0-9A-Fa-f]{2}[:-])" +
             "{5}([0-9A-Fa-f]{2})|" +
             "([0-9a-fA-F]{4}\\." +
             "[0-9a-fA-F]{4}\\." +
             "[0-9a-fA-F]{4})$")

    # Compile the ReGex
    p = re.compile(regex)

    if mac:
        if(re.search(p, str)):
            return True
        else:
            return False
