#!/data/data/com.termux/files/usr/bin/bash

if [ $# -lt 1 ]
then
    dir=$PWD
else
    dir=$1
fi

for i in `find $dir -maxdepth 1 -type f`
do
    echo $i
    echo '————————————————————————————————'
    cat $i
    echo -e '\n\n'
done
