COMPRESS_FILENAME_TEMPLATE="%name_%date.%ext"
COMPRESS_COMPRESSION_METHOD="7z"
COMPRESS_COMPRESSION_LEVEL="5"
COMPRESS_PASSWORD=""
IMAGE_OUTPUT_FORMAT="jpeg"
IMAGE_MAX_RESOLUTION="1280x720"
IMAGE_RESIZE_MODE="fit"
IMAGE_SCALE_FLAGS="lanczos"
IMAGE_STRIP_METADATA="0"
IMAGE_OUTPUT_TEMPLATE="%name_reduced.%ext"
IMAGE_JPEG_QUALITY="10"
IMAGE_JPEG_PROGRESSIVE="0"
IMAGE_JPEG_OPTIMIZE="0"
IMAGE_JPEG_SUBSAMPLING="420"
IMAGE_PNG_COMPRESSION="2"
IMAGE_PNG_PRED="mixed"
IMAGE_PNG_PALETTE_MODE="0"
IMAGE_WEBP_QUALITY="75"
IMAGE_WEBP_LOSSLESS="0"
IMAGE_WEBP_COMPRESSION_LEVEL="4"
IMAGE_WEBP_PRESET="photo"
IMAGE_WEBP_ALPHA_QUALITY="80"
